version: '3.5'
services:
  redis:
    container_name: redis-fiap
    hostname: redis-fiap
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: mysql:5.7
    container_name: redis-mysql
    restart: always
    environment:
      MYSQL_DATABASE: fiap
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
